spring:
  data:
    mongodb:
      username: marcazia_mongo_user
      password: marcazia_password
      host: localhost
      port: 27019
      authentication-database: admin
      database: notification
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: paymentGroup, OrderGroup
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.type.mapping: >
          orderConfirmation:com.marcazia.notification.kafka.order.OrderConfirmation,
          paymentConfirmation:com.marcazia.notification.kafka.payment.PaymentConfirmation
        spring.json.trusted.packages: "*"
  mail:
    host: localhost
    port: 1025
    username: marcazia_email_user
    password: marcazia_email_password
    properties:
      mail:
        smtp:
          trust: "*"
          auth: true
          starttls:
            enabled: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000

server:
  port: 8040

