server:
  port: 8090

spring:
  data:
    mongodb:
      uri: mongodb://marcazia_mongo_user:marcazia_password@${MONGO_HOST:localhost}:${MONGO_PORT:27019}/${MONGO_DB:customerdb}?authSource=admin
      database: ${MONGO_DB:customerdb}
